### ISSUE TITLE
About the file 'train_mf.txt'

### ISSUE THREAD

**Issue by PainLiu** [ZhengPeng7/motion_magnification_learning-based#1]
Thanks for sharing the code. 
But it is confused for me to find the 'train_mf.txt' file, could you tell me where is the file? Thanks a lot.

**Comment by ZhengPeng7** [comment]
The "_mf" means the magnification factor, so it's the file along with the coco image triplets given by the MIT' official project page, Here is the download [link](https://groups.csail.mit.edu/graphics/deep_motion_mag/data/readme.txt)

**Comment by PainLiu** [comment]
> The "_mf" means the magnification factor, so it's the file along with the coco image triplets given by the MIT' official project page, Here is the download [link](https://groups.csail.mit.edu/graphics/deep_motion_mag/data/readme.txt)

问题已解决，谢谢！
