### ISSUE TITLE
为啥是蓝色效果

### ISSUE THREAD

**Issue by anyu-20210425** [ZhengPeng7/motion_magnification_learning-based#10]
为什么我的测试文件运行出来是蓝色的视频，修改代码里面的colour那改了不起作用，是因为没有训练模型的原因吗，模就是蓝色的通道吗

**Comment by ZhengPeng7** [comment]
不懂什么意思, 请把视频, 修改代码的位置 给出. 还有"模就是蓝色的通道"是什么意思...

**Comment by anyu-20210425** [comment]
哇，你回复了真是太好了，这个问题困扰我好几天了，就是我只是测试跑通了，运行出来的结果是蓝色的视频，少打了一个字是因为模型就是蓝色的通道吗，我没有训练模型，只是测试，还想问下作者这个模型训练涉及到什么庞大的数据集了吗，下面是代码位置改这里不顶用还报错，是test-video.py文件里的代码最下面那









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peng ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZhengPeng7/motion_magnification_learning-based] 为啥是蓝色效果 (Issue #10)





 
不懂什么意思, 请把视频, 修改代码的位置 给出. 还有"模就是蓝色的通道"是什么意思...

**Comment by ZhengPeng7** [comment]
不是呀, 我之前跑出来的效果就像README里的gif图. 我觉得你要不去检查一下测试视频分解下来的frame? 如果不行, 可以试一下改下通道试试? 我最近太累了, 而且项目太久了. 我看看吧, 这几天如果有精力的话写个colab, 如果有的话我到时回复你.

**Comment by anyu-20210425** [comment]
嗯嗯好的谢谢，我是课题需要，这个只能运动放大吗能不能实现视频颜色增强，我也不知道我的为什么跑出来是这种蓝色的视频，觉得好不容易跑通的居然是这样的可能都没法用了，我编程基础比较差不太会检查你说的这个，如果你有时间的话能不能抽空联系我远程帮我看一下这是哪的代码出了问题啊看看能不能改好，我找我同学帮我看代码他们都不会这个万分感谢，你不用写出来也行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peng ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 晚上9:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZhengPeng7/motion_magnification_learning-based] 为啥是蓝色效果 (Issue #10)





 
不是呀, 我之前跑出来的效果就像README里的gif图. 我觉得你要不去检查一下测试视频分解下来的frame? 如果不行, 可以试一下改下通道试试? 我最近太累了, 而且项目太久了. 我看看吧, 这几天如果有精力的话写个colab, 如果有的话我到时回复你.

**Comment by ZhengPeng7** [comment]
你可以去看下原论文对这个synthetic数据集的介绍, 这个数据集只针对运动的放大, 没有颜色相关的事. 检查代码的话我应该是真不太有时间去debug。。。 你就先确保数据本身, 环境 这些一致. 代码直接跑应该是没问题的.

**Comment by ZhengPeng7** [comment]
Hi, 今天突然想到了这事, 我更新了colab demo, 上传视频指定下后, 一键全run就可以产出运动放大后的视频了，colab的链接在README. 过了很久, 不知道你还用不用得上哈.
<img width="1702" alt="VMM_colab_demo" src="https://user-images.githubusercontent.com/25921713/230589573-68d65731-ff7a-4b34-9aa3-e29b4dc6db4b.png">
