### ISSUE TITLE
关于放大SAMM数据集

### ISSUE THREAD

**Issue by RuowangLIu** [ZhengPeng7/motion_magnification_learning-based#14]
我有一个疑问，为什么我使用视频放大SAMM数据集得到的结果并不明显，是因为每帧之间的差别不够大嘛，而且放大后的视频像素质量有所下降

**Comment by RuowangLIu** [comment]
如您所讲
![006_05632](https://github.com/ZhengPeng7/motion_magnification_learning-based/assets/105041125/f809b88a-d87f-44b1-966f-c365d6784a10)
![006_055881 (2)](https://github.com/ZhengPeng7/motion_magnification_learning-based/assets/105041125/973e52c7-e69e-4be4-9575-5501970d13de)
图一是视频放大之后，针对顶帧做的光流图像，人物的变化不大，但是周围的噪声变化太大了，请问有啥好建议嘛，减少噪声增大面部表情的变化

**Comment by ZhengPeng7** [comment]
在learning-based VMM中, 他们是用的temporal filter能选择不同frequency下的动作, 从而减少了很多噪声. 至于我的想法就更直接一些, 可以把人物分割出来, 只放大他... 外轮廓部分用inpainting补足.

**Comment by ZhengPeng7** [comment]
有想法欢迎继续留言...
