### ISSUE TITLE
Pre trained check point

### ISSUE THREAD

**Issue by yxiao54** [ZhengPeng7/motion_magnification_learning-based#2]
Is it possible to provide a pre-trained check point on github? I'm very interest in your code. Your code is in compact structure and easy to understand.  I think it would be great if your can provide a pre-trained check point.

**Comment by ZhengPeng7** [comment]
Very glad to have your interest:)
Actually, you can download the weights of the well-trained model in the [release](https://github.com/ZhengPeng7/motion_magnification_learning-based/releases/tag/v1.0), I remember that I used this one to generate the GIFs in the README.
