### ISSUE TITLE
Synthetic data set

### ISSUE THREAD

**Issue by shanchao0906** [ZhengPeng7/motion_magnification_learning-based#3]
Hello, excuse me, is the synthetic data set easy to share?

**Comment by ZhengPeng7** [comment]
Sure, you can refer to [the official codes](https://github.com/12dmodel/deep_motion_mag) or [the official project site](https://people.csail.mit.edu/tiam/deepmag/) for it. But one thing to mention, the dataset is very big, containing about 12 zip files, which are totally 80+G.
