### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by shanchao0906** [ZhengPeng7/motion_magnification_learning-based#4]
Can you share the dataset
There are some problems downloading the official link
thank you

**Comment by ZhengPeng7** [comment]
Hi, what problem did you meet? I just made the download from the official link, but it worked fine...

**Comment by shanchao0906** [comment]
An error is reported when unzipping the zip package
Prompt data corruption
Is the JSON file containing the amplification factor downloaded from the same link？

**Comment by ZhengPeng7** [comment]
It might be that you met interruption in downloading and some packages are incomplete. Check the single ones and download it again, it may go right.

As I remember, the amplification factors were contained in the JSON file, but there seems to be another text file that only contains amplification factors, I used that one.

**Comment by ZhengPeng7** [comment]
Sorry for that I took it for granted. JSON file doesn't contain the amp_factors. The factors are in a single txt file called `train_mf.txt`.

I provide the [link](https://drive.google.com/drive/folders/1X07ElPSDHk7j0osgt6-i_cMRpfWvNOLM?usp=sharing) to the folder containing the datasets of this project on my personal google-drive.

It contains:
1. `amplified.zip (22.5G)`,
2. `frameA.zip (23.1G)`,
3. `frameB.zip (22.6G)`,
4. `frameC.zip (22.7G)`,
5. `train_mf.txt`,
6. `train_vid_frames.zip(3.4G, the frames of some validation videos such as baby, drone)`.
> The meta zip file was not uploaded since I didn't use it, but will be also added later.

Now it's being uploaded, it may take some time.
