### ISSUE TITLE
 normalization

### ISSUE THREAD

**Issue by shanchao0906** [ZhengPeng7/motion_magnification_learning-based#5]
Sorry, I can't find the code that normalizes the input picture in your code.
Is there no normalization?

**Comment by ZhengPeng7** [comment]
https://github.com/ZhengPeng7/motion_magnification_learning-based/blob/207c010feef094a2efabd1ad3c9543722c7af81d/data.py#L48

**Comment by shanchao0906** [comment]
ok ,thank you
