### ISSUE TITLE
Hellow，Zheng，I have a problem when running "test_video.py"

### ISSUE THREAD

**Issue by Jiafei127** [ZhengPeng7/motion_magnification_learning-based#6]
data.py, line 86, in get_paths_ABC
    dir_root = eval('config.dir_{}'.format(val_vid))
  File "<string>", line 1, in <module>
AttributeError: 'Config' object has no attribute 'dir_'

I like your project very much, can you answer my question？

**Comment by ZhengPeng7** [comment]
Thanks a lot for your interest.

Plz assign some value to the `val_vid` to make dir_root as `eval('config.dir_guitar')`, so that you can test on the video frames of the guitar video of which the result is shown in README.

**Comment by Jiafei127** [comment]
> 

Thank you very much for your reply. You are so amazing, I admire you very much. Your code also inspired me deeply as a beginner, and I look forward to asking you in the follow-up study. Thanks!
