### ISSUE TITLE
您好，请问可以用该代码帮助我处理几个视频吗？（不胜感激）

### ISSUE THREAD

**Issue by xxdragon163** [ZhengPeng7/motion_magnification_learning-based#7]
楼主您好！
我目前在回复小论文的审稿意见，需要用该代码处理6个视频，作为对比结果。
由于我目前还未掌握深度学习的用法，时间上有些来不及，您能帮助我用该深度学习算法处理一下这些视频吗？
非常感谢。

张龙
邮箱：785608724@qq.com
PS>如果可以的话，麻烦您通过邮箱联系我，我将视频文件由邮箱发送给您。再次感谢。

**Comment by ZhengPeng7** [comment]
不好意思啊, 最近用机器不是很方便, 我现在也没当时的环境, 我自己这几天赶ECCV时间也非常紧. 你如果对深度学习不了解的话, 那就用mit主页上的phase-based 的效果就不错了.
https://people.csail.mit.edu/mrub/vidmag
近期的事了结后, 我尽量弄个colab作为在线demo, 但是现在真的没时间去整了. Good Luck.

**Comment by xxdragon163** [comment]
感谢回复 我调通啦 嘿嘿



在 2022-02-28 22:01:26，"Peng Zheng" ***@***.***> 写道：

不好意思啊, 最近用机器不是很方便, 我现在也没当时的环境, 我自己这几天赶ECCV时间也非常紧. 你如果对深度学习不了解的话, 那就用mit主页上的phase-based 的效果就不错了.
https://people.csail.mit.edu/mrub/vidmag
近期的事了结后, 我尽量弄个colab作为在线demo, 但是现在真的没时间去整了. Good Luck.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZhengPeng7** [comment]
恭喜恭喜哈🏮

xxdragon163 ***@***.***> 于2022年4月19日周二 10:34写道：

**Comment by ZhengPeng7** [comment]
The link to the Colab demo has been added in README.
