### ISSUE TITLE
color magnified

### ISSUE THREAD

**Issue by To-the-bone** [ZhengPeng7/motion_magnification_learning-based#8]
Does the code create color magnification?

**Comment by ZhengPeng7** [comment]
Currently, there is no such a training set for color magnification. But if you have it, the overall pipeline is still the same.
You can check this issue [responsed](https://github.com/12dmodel/deep_motion_mag/issues/15#issuecomment-662888957) by the first author of this paper.

**Comment by To-the-bone** [comment]
Thanks for your answer

**Comment by ZhengPeng7** [comment]
You are welcome.
