### ISSUE TITLE
How to form a 'magnet.pt' file?

### ISSUE THREAD

**Issue by qufy6** [ZhengPeng7/motion_magnification_learning-based#9]
Hi, I met some questions and I need ur help.
I came from `https://github.com/Justin900429/Facial-Graph-Representation-Learning` , and I cloned your project under file `weight`.
I need to use a file named `magnet.pt`, `like this :**self.magnet.load_state_dict(torch.load("weight/magnet.pt", map_location=device))**` could u plz tell me that how can I get such a file?(I've read ur code, not finding the name...

**Comment by ZhengPeng7** [comment]
Oh, glad to see that my codes can do some help. I think you have found it in the release of this project, GL.
